# Generated by Django 6.0.4 on 2026-04-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_shopmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
