# Generated by Django 6.0.4 on 2026-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("expired", "Expiré"),
                    ("inactive", "Inactif"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
