# Generated by Django 6.0.4 on 2026-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
    ]
