# Generated by Django 6.0.4 on 2026-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_saleitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="cancel_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[("validated", "Validée"), ("cancelled", "Annulée")],
                default="validated",
                max_length=20,
            ),
        ),
    ]
