# Generated by Django 6.0.4 on 2026-04-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_sale_amount_paid_sale_customer_sale_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
