# Generated by Django 6.0.4 on 2026-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="supplier",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
